### PR TITLE
fix: Use correct tokenUrl and fix typos (Sass -> SaaS)

### LINKED ISSUE #244: Unable to create aquasec_role_mapping_saas
### Terraform Version
terraform 1.3.7
terraform-provider-aquasec_v0.8.24

### Affected Resource(s)
Please list the resources as a list, for example:
- aquasec_role_mapping_saas

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aquasec_role_mapping_saas" "post_user" {
  csp_role = aquasec_role.post_user.role_name

  saml_groups = [
    "xxx",
    "yyy"
  ]
}
```

### Debug Output
`---`

### Panic Output
`---`

### Expected Behavior
TF runs without errors, mapping is created

### Actual Behavior

```log
Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
aquasec_role_mapping_saas.post_user: Creating...
aquasec_role_mapping_saas.post_admin: Creating...
╷
│ Error: error calling /v2/samlmappings, error: {"status":403,"id":"00000000-0000-0000-0000-000000000000","code":1,"message":"Access denied","errors":["The request is missing the session token. Please login."]}
│ 
│   with aquasec_role_mapping_saas.post_admin,
│   on access.tf line 98, in resource "aquasec_role_mapping_saas" "post_admin":
│   98: resource "aquasec_role_mapping_saas" "post_admin" {
│ 
╵
╷
│ Error: error calling /v2/samlmappings, error: {"status":403,"id":"00000000-0000-0000-0000-000000000000","code":1,"message":"Access denied","errors":["The account session is malformed. Please login again."]}
│ 
│   with aquasec_role_mapping_saas.post_user,
│   on access.tf line 107, in resource "aquasec_role_mapping_saas" "post_user":
│  107: resource "aquasec_role_mapping_saas" "post_user" {
│ 
╵
```

~One thing that I observe while creating it via the UI is that the HTTP method (PUT vs. POST) could be wrong?: [sso.go](https://github.com/aquasecurity/terraform-provider-aquasec/blob/79ee7432ab41d55609039d9896177dd6ebe1e01e/client/sso.go#L268)~

(func `createSsoBasic()` seems to be used only in non-SaaS environment)

### Steps to Reproduce
Define aquasec_role_mapping_saas and apply it.

### Important Factoids
SaaS platform

### References
`---`

### PR DESCRIPTION
**Pull request by mkilchhofer**
It seems that the resource `aquasec_role_mapping_saas` today only works for the default SaaS region. The other regions `eu-1`, `asia-1` and `asia-2` cannot work with todays implementation.

Fixes #244
While here, I also fixed typos inside class names and comments.

Before change:
wrong token API baseurl

After change:
correct token API baseurl
(Traces/screenshots are made using [github.com/mitmproxy](https://github.com/mitmproxy/mitmproxy).)

/cc: @BaruchBilanski , @yossig-aquasec , @blanchardma , @the-technat

### CODE REVIEW

File: client/sso.go [hunk 1]
```diff
@@ -279,22 +280,17 @@ func (cli *Client) createSsoBasic(apiPath string, sso interface{}) error {
...
-		baseUrl = consts.SaasTokenUrl
-	default:
-		err = fmt.Errorf("GetRoleMappingSass is Supported only in Aqua SASS env")
+
+	if cli.clientType == Saas || cli.clientType == SaasDev {
+		baseUrl = cli.tokenUrl
+	} else {
+		err = fmt.Errorf("GetRoleMappingSaas is Supported only in Aqua SaaS env")
 		return nil, err
 	}
```
Comment (mkilchhofer) [inline client/sso.go:295]: These codeblocks fixes the issue #244. They already existed in `group.go` and `user.go`

**Review by semyonmor — APPROVED** [review]

**Comment by mkilchhofer** [comment]
@semyonmor thx for merging this!

Can you trigger a release build now? Waiting for it :)
